name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - numpy=1.19
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - numpy=1.19
  - pip:
      - wandb==0.10.21
